name: Pre-Merge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check target branch (main)
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          if [[ "$SOURCE_BRANCH" != "staging" ]]; then
            echo "Only the staging branch can be merged into the $TARGET_BRANCH branch."
            exit 1
          fi
          
          echo "Pull request target branch is valid."

      - name: Check target branch (staging)
        if: ${{ github.event.pull_request.base.ref == 'staging' }}
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
              
          if [[ "$SOURCE_BRANCH" != "dev" && "$SOURCE_BRANCH" != "main" ]]; then
            echo "Only the dev or main branches can be merged into the staging branch."
            exit 1
          fi
                
          echo "Pull request target branch is valid."

  eslint-prettier:
    runs-on: ubuntu-latest
    needs: check-target-branch
    if: ${{ github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'staging' || github.event.pull_request.base.ref == 'main' }}
    permissions:
      contents: write
      security-events: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Authenticate remote origin
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/AX-AI-LTD/winston-cloudwatch-logger-config.git

      - name: Install ESLint and Prettier
        run: |
          npm install eslint@8.57.0
          npm install prettier

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier
        run: npm run format

      - name: Amend Commit and Push
        shell: bash
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "No Eslint and Prettier changes made"
          else
            echo "Eslint and Prettier Changes made"
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Action"
            git add .
            git commit --amend --no-edit
            git push -f origin
          fi

  run-tests:
    runs-on: ubuntu-latest
    needs: check-target-branch
    if: ${{ github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'staging' || github.event.pull_request.base.ref == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
